# Atividade 03

## Lucas de Lucena Siqueira - 201080354

Criar o modelo e as métricas, comparando com o modelo original (Arquivo SelecaoDeAtributos-v2021.ipynb)


## Carregando o Dataset Boston Houses
1. CRIM: per capita crime rate by town 
2. ZN: proportion of residential land zoned for lots over 25,000 sq.ft. 
3. INDUS: proportion of non-residential acres per town 
4. CHAS: Charles River dummy variable (= 1 if tract bounds river; 0 otherwise) 
5. NOX: nitric oxides concentration (parts per 10 million) 
6. RM: average number of rooms per dwelling 
7. AGE: proportion of owner-occupied units built prior to 1940 
8. DIS: weighted distances to five Boston employment centres 
9. RAD: index of accessibility to radial highways 
10. TAX: full-value property-tax rate per 10,000 
11. PTRATIO: pupil-teacher ratio by town 
12. B: 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town 
13. LSTAT: % lower status of the population 
14. TARGET: Median value of owner-occupied homes in $1000's

In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl
from sklearn.datasets import load_boston
from sklearn import linear_model
from sklearn.metrics import r2_score
from sklearn.preprocessing import StandardScaler
%matplotlib inline 

In [12]:
# Gerando o dataset
import pandas as pd
from sklearn.datasets import load_boston

boston = load_boston() 
dataset = pd.DataFrame(boston.data, columns = boston.feature_names)
dataset['target'] = boston.target
dataset.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4  
4     18.7  396.90   5.33    36.2

In [13]:
dataset.iloc[:,:-1][:3]

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03

In [14]:
# aplicando a RFE
from sklearn.feature_selection import RFE
from sklearn.svm import SVR


X = dataset.iloc[:,:-1].values
y = dataset['target'].values
num_atributos_relevantes = 8
estimator = SVR(kernel="linear")
selector = RFE(estimator, num_atributos_relevantes, step=1)
selector = selector.fit(X, y)

print("Num Features: ", selector.n_features_)
print("Selected Features: ", selector.support_)
print("Feature Ranking: ", selector.ranking_)

C:\Users\lucaslucena\Anaconda3\lib\site-packages\sklearn\utils\validation.py:70: FutureWarning: Pass n_features_to_select=8 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  warnings.warn(f"Pass {args_msg} as keyword args. From version "


Num Features:  8
Selected Features:  [ True False  True  True  True  True False  True False False  True False
  True]
Feature Ranking:  [1 2 1 1 1 1 3 1 5 6 1 4 1]


In [15]:
X = dataset.copy()
X.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4  
4     18.7  396.90   5.33    36.2

In [16]:
atributos = list(dataset.columns[:-1])
atributos

['CRIM',
 'ZN',
 'INDUS',
 'CHAS',
 'NOX',
 'RM',
 'AGE',
 'DIS',
 'RAD',
 'TAX',
 'PTRATIO',
 'B',
 'LSTAT']

Importância dos Atributos
target 1.000000
LSTAT 0.737663
RM 0.695360
PTRATIO 0.507787
INDUS 0.483725
TAX 0.468536
NOX 0.427321
CRIM 0.388305
RAD 0.381626
AGE 0.376955
ZN 0.360445
B 0.333461
DIS 0.249929
CHAS 0.175260

In [17]:
atributos = ['CRIM',
 'ZN',
 'INDUS',
 'CHAS',
 'NOX',
 'RM',
 'AGE',
 'DIS',
 'RAD',
 'TAX',
 'PTRATIO',
 'B',
 'LSTAT']

X = X[ atributos ]
X.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [18]:
# Criando um modelo
modelo = linear_model.LinearRegression()
modelo.fit(X,y)

LinearRegression()

In [20]:
modelo.coef_

array([-1.08011358e-01,  4.64204584e-02,  2.05586264e-02,  2.68673382e+00,
       -1.77666112e+01,  3.80986521e+00,  6.92224640e-04, -1.47556685e+00,
        3.06049479e-01, -1.23345939e-02, -9.52747232e-01,  9.31168327e-03,
       -5.24758378e-01])

In [21]:
for coef, var in sorted(zip(modelo.coef_, dataset.columns[:-1]), reverse = True):
    print ("%6.3f %s" % (coef,var))

 3.810 RM
 2.687 CHAS
 0.306 RAD
 0.046 ZN
 0.021 INDUS
 0.009 B
 0.001 AGE
-0.012 TAX
-0.108 CRIM
-0.525 LSTAT
-0.953 PTRATIO
-1.476 DIS
-17.767 NOX


# Avaliando o modelo com o R Squared (R²) 

In [23]:
def r2_est(X,y):
    modelo = linear_model.LinearRegression(normalize = False, fit_intercept = True)
    return r2_score(y, modelo.fit(X,y).predict(X))

print ('R2: %0.3f' %  r2_est(X,y))

R2: 0.741


# Métricas para Algoritmos de Regressão
Gerando o dataset

In [25]:
dataset['y_prev'] = modelo.predict(X)

dataset.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target     y_prev  
0     15.3  396.90   4.98    24.0  30.003843  
1     17.8  396.90   9.14    21.6  25.025562  
2     17.8  392.83   4.03    34.7  30.567597  
3     18.7  394.63   2.94    33.4  28.607036  
4     18.7  396.90   5.33    36.2  27.943524

In [26]:
dataset['Erro'] = abs (dataset['y_prev'] - dataset['target'] )
dataset.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target     y_prev      Erro  
0     15.3  396.90   4.98    24.0  30.003843  6.003843  
1     17.8  396.90   9.14    21.6  25.025562  3.425562  
2     17.8  392.83   4.03    34.7  30.567597  4.132403  
3     18.7  394.63   2.94    33.4  28.607036  4.792964  
4     18.7  396.90   5.33    36.2  27.943524  8.256476

In [27]:
dataset.head(10)

CRIM    ZN  INDUS  CHAS    NOX     RM    AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575   65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421   78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185   61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998   45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147   54.2  6.0622  3.0  222.0   
5  0.02985   0.0   2.18   0.0  0.458  6.430   58.7  6.0622  3.0  222.0   
6  0.08829  12.5   7.87   0.0  0.524  6.012   66.6  5.5605  5.0  311.0   
7  0.14455  12.5   7.87   0.0  0.524  6.172   96.1  5.9505  5.0  311.0   
8  0.21124  12.5   7.87   0.0  0.524  5.631  100.0  6.0821  5.0  311.0   
9  0.17004  12.5   7.87   0.0  0.524  6.004   85.9  6.5921  5.0  311.0   

   PTRATIO       B  LSTAT  target     y_prev      Erro  
0     15.3  396.90   4.98    24.0  30.003843  6.003843  
1     17.8  396.90   9.14    21.6  25.025562  3.425562  
2     17.8  392.83   4.03    34.7  30.567597  4.132403  
3     18.7  394.63   2.94    33.4  28.607036  4.792964  
4     18.7  396.90   5.33    36.2  27.943524  8.256476  
5     18.7  394.12   5.21    28.7  25.256284  3.443716  
6     15.2  395.60  12.43    22.9  23.001808  0.101808  
7     15.2  396.90  19.15    27.1  19.535988  7.564012  
8     15.2  386.63  29.93    16.5  11.523637  4.976363  
9     15.2  386.71  17.10    18.9  18.920262  0.020262

In [28]:
dataset.Erro.sum()

1655.0565823155603

In [30]:
print(dataset.shape)


(506, 16)


## MAE - Mean Absolute Error
É a soma da diferença absoluta entre previsões e valores reais.<br />
Fornece uma ideia de quão erradas estão nossas previsões.<br />
Valor igual a 0 indica que não há erro, sendo a previsão perfeita <br />
(a exemplo do Logloss, a função cross_val_score inverte o valor) 

In [31]:
from sklearn import model_selection
num_folds = 39
num_instances = len(X)
seed = 15

# Separando os dados em folds
kfold = model_selection.KFold(num_folds, True, random_state = seed)
resultado = model_selection.cross_val_score(modelo, X, y, cv = kfold, 
                                            scoring = 'neg_mean_absolute_error')

# Print do resultado
print("MAE: %.3f (%.3f)" % (resultado.mean(), resultado.std()))

C:\Users\lucaslucena\Anaconda3\lib\site-packages\sklearn\utils\validation.py:70: FutureWarning: Pass shuffle=True as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  warnings.warn(f"Pass {args_msg} as keyword args. From version "


MAE: -3.394 (0.922)


In [32]:
resultado

array([-4.18697907, -2.08923472, -3.18363222, -3.7614362 , -3.19397272,
       -1.52381741, -5.1048777 , -5.08811661, -3.96605435, -5.16308534,
       -3.47484933, -3.30915297, -3.14767813, -2.69519848, -2.30820926,
       -3.67471263, -3.64253366, -3.70426882, -2.81143274, -4.55148864,
       -4.94755769, -3.22358895, -4.23140924, -2.72511995, -1.93977719,
       -3.1240936 , -2.91551155, -3.07665534, -2.61020172, -4.49081277,
       -2.92750354, -2.96027884, -1.88987024, -3.53258648, -4.42471784,
       -2.66993093, -3.68847424, -2.25297621, -4.15643672])

## MSE - Mean Squared Error
Similar ao MAE, fornece a magnitude do erro do modelo.<br />
Ao extrairmos a raiz quadrada do MSE convertemos as unidades de volta ao original, 
o que pode ser útil para descrição e apresentação.<br />
Isso é chamado RMSE (Root Mean Squared Error)

In [33]:
# Definindo os valores para o número de folds
num_folds = 39
num_instances = len(X)
seed = 15

# Separando os dados em folds
kfold = model_selection.KFold(num_folds, True, random_state = seed)

resultado = model_selection.cross_val_score(modelo, X, y, cv = kfold, scoring = 'neg_mean_squared_error')

# Print do resultado
print("MSE: %.3f (%.3f)" % (resultado.mean(), resultado.std()))

C:\Users\lucaslucena\Anaconda3\lib\site-packages\sklearn\utils\validation.py:70: FutureWarning: Pass shuffle=True as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  warnings.warn(f"Pass {args_msg} as keyword args. From version "


MSE: -23.783 (16.221)


In [34]:
resultado

array([-27.98399002,  -6.63717961, -14.80237239, -25.52584986,
       -14.35346296,  -4.81877321, -39.36021421, -43.21849793,
       -54.79484948, -51.76312333, -27.86825618, -16.69445872,
       -23.48518759, -10.59720772, -10.72682068, -19.85020877,
       -24.37785915, -27.90261899, -12.06511282, -68.65361235,
       -71.6556045 , -15.86502242, -31.82872638, -10.17270165,
        -7.37832126, -14.4831941 , -16.65302631, -15.70099033,
       -10.01663314, -33.44301448, -19.60090474, -17.45215659,
        -6.05830868, -17.38566565, -36.44127858,  -9.72321991,
       -32.77807086,  -8.38261299, -27.02773811])

# RMSE (Root Mean Squared Error)
Similar ao MAE, fornece a magnitude do erro do modelo.<br>
Ao extrairmos a raiz quadrada do MSE convertemos as unidades de volta ao original, o que pode ser útil para descrição e apresentação.

In [36]:
from math import sqrt
print("RMSE: %.3f " % (sqrt(abs(resultado.mean()))))

RMSE: 4.877 


## R2  
Essa métrica fornece uma indicação do nível de precisão das previsões em relação aos valores observados.<br />
Também chamado de coeficiente de determinação.<br />
Valores entre 0 e 1, sendo 1 o valor ideal.

In [37]:
resultado = model_selection.cross_val_score(modelo, X, y, cv = kfold, scoring = 'r2')

# Print do resultado
print("R^2: %.3f (%.3f)" % (resultado.mean(), resultado.std()))

R^2: 0.655 (0.257)


In [38]:
resultado

array([ 0.62806621,  0.91877628, -0.36324055,  0.6479354 ,  0.81621185,
        0.91697902,  0.73769046,  0.30362662,  0.2971991 ,  0.71840447,
        0.30954649,  0.82280249,  0.45873234,  0.7148358 ,  0.88947315,
        0.66608817,  0.71418138,  0.81011365,  0.58022381,  0.28449569,
        0.32681387,  0.85823702,  0.76337643,  0.88176776,  0.89615908,
        0.8059375 ,  0.84440537,  0.61813031,  0.71818985,  0.65456119,
        0.81985834,  0.5718661 ,  0.82017771,  0.64211688,  0.23594849,
        0.88592809,  0.66332796,  0.8864059 ,  0.76959378])